services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./models:/root/.ollama/models  # Optional: for custom model storage
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    # Intel Mac optimizations
    deploy:
      resources:
        limits:
          memory: 8G  # Adjust based on your RAM
        reservations:
          memory: 2G
    command: "serve"
  #python3 -c "import secrets; print(secrets.token_urlsafe(32))"
    # Vector Database - Qdrant
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    # Alternative: Sentence Transformers API
  embedding-api:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.2
    container_name: embedding-api
    ports:
      - "8080:80"
    environment:
      - MODEL_ID=sentence-transformers/all-MiniLM-L6-v2
      - REVISION=main
      - MAX_CONCURRENT_REQUESTS=512
      - MAX_BATCH_TOKENS=16384
    restart: unless-stopped
    # For CPU inference on Intel Mac
    command: --model-id sentence-transformers/all-MiniLM-L6-v2 --port 80

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    restart: unless-stopped  

  # Optional: Web UI for easier interaction
  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
    depends_on:
      - ollama
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped

volumes:
  ollama_data:
    driver: local
  open-webui:
    driver: local
  chroma_data:
    driver: local
  qdrant_data:
    driver: local
    