services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./models:/root/.ollama/models  # Optional: for custom model storage
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    # Intel Mac optimizations
    deploy:
      resources:
        limits:
          memory: 8G  # Adjust based on your RAM
        reservations:
          memory: 2G
    command: "serve"
  
  # Optional: Web UI for easier interaction
  # ollama-webui:
  #   image: ghcr.io/open-webui/open-webui:main
  #   container_name: webui
  #   ports:
  #     - "3000:8080"
  #   environment:
  #     - OLLAMA_BASE_URL=http://ollama:11434
  #     - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
  #   depends_on:
  #     - ollama
  #   volumes:
  #     - open-webui:/app/backend/data
  #   restart: unless-stopped

volumes:
  ollama_data:
    driver: local
  # open-webui:
  #   driver: local
    